### ISSUE TITLE
Draft Official Release for Tag v1.0.0

### ISSUE THREAD

**Issue by markrogoyski** [TeleSign/php_telesign#12]
Can you draft an official release for tag v1.0.0? It does not show up on Packagist as a valid release and therefore it can't be installed via Composer. If you try to require v1.0.0 and install with Composer, you will get the following error:
`The requested package telesign/telesign v1.0.0 exists as telesign/telesign[dev-master, v2.0.0, v2.1.0] but these are rejected by your constraint.`

Thanks.

**Comment by erikkai** [comment]
Hi Mark, 

Can you provide more detail about what you're working on? TeleSign encourages you to use the latest SDKs as they're all up to date. Without much info, some things I can think of that might address your situation: 

1. If you're doing a free trial or you are a customer but not an Enterprise customer), you will want the latest PHP SDK (so the 2.0.0 tag) because that contains all TeleSign's new product offerings.
2. If you want to use Enterprise products the latest PHP SDK is in a private repository. If you're already a customer you can ask your TAM for access. If you are new, then write to support@telesign.com for help getting access. 

-Erikka

**Comment by markrogoyski** [comment]
Hi Erikka,

Thank you for the response. We have some legacy code we are working with that was manually including the v1.0.0 code. We want to use Composer in our workflow to handle our 3rd-party libraries, but Telesign v1.0.0 is unable to be installed using Composer.

Updating to the latest version sounds like a prudent thing to do, but as a first step we'd like to get the existing code to work via Composer before changing versions.

Would it be possible to draft a release for the existing v1.0.0 tag and refresh Packagist so the version becomes available to Composer?

Thanks.

**Comment by erikkai** [comment]
I sent a note asking the team about this - we are heading into the weekend so I will check again with them on Monday.

**Comment by luka-zitnik** [comment]
Hi Mark,

You can "inline package definition" in your legacy project's composer.json, like this, https://gist.github.com/luka-zitnik/735e5b3b001cd6dafbe2684559011faf

This is not an official statement from TeleSign, but only my own remark.

**Comment by KristopherWindsor** [comment]
Hi Luka,

We are currently doing it that way, with a custom repository definition. But, it seems like a hack a bit.

Hopefully TeleSign can publish the existing v1.0.0 git tag as a release?

**Comment by luka-zitnik** [comment]
Hi Kristopher,

I have the patch in a fork, but still don't have the approval.

**Comment by luka-zitnik** [comment]
https://github.com/TeleSign/php_telesign/tree/v1.1.0

**Comment by KristopherWindsor** [comment]
Thanks!

**Comment by luka-zitnik** [comment]
Should have used classpath instead of files. Let me know if that's an issue to you.

**Comment by KristopherWindsor** [comment]
Hi, classmap would be a little nicer, but I think the performance impact of using "files" won't be noticed.

Thanks,

**Comment by luka-zitnik** [comment]
I'll leave it then. Thank you.
